import CurveComplexGenusTwo.CWHurewicz.SmallSingularChainsLocal

set_option maxHeartbeats 1000000

namespace CurveComplexGenusTwo.CWHurewicz

open CategoryTheory Convexity
open scoped Simplicial

private abbrev SingularFree (X : TopCat) (n : ℕ) :=
  (TopCat.toSSet.obj X) _⦋n⦌ →₀ ℤ

private theorem iterateList_eq_iterate (X : TopCat) (n k : ℕ)
    (c : SingularFree X n) :
    singularBarycentricIterateList X n k c =
      singularBarycentricIterate X n k c := by
  induction k with
  | zero => rfl
  | succ k ih =>
      change singularBarycentricFinsupp X n
          (singularBarycentricIterateList X n k c) =
        singularBarycentricFinsupp X n (singularBarycentricIterate X n k c)
      rw [ih]

/-- A singular simplex belongs to one member of the excision cover. -/
def SmallSingularSimplex (X : TopCat) (A U : Set X) (n : ℕ)
    (x : (TopCat.toSSet.obj X) _⦋n⦌) : Prop :=
  Set.range (TopCat.toSSetObjEquiv X (.op ⦋n⦌) x) ⊆ Uᶜ ∨
    Set.range (TopCat.toSSetObjEquiv X (.op ⦋n⦌) x) ⊆ A

/-- The free subgroup generated by singular simplices carried by one cover member. -/
def smallSingularChains (X : TopCat) (A U : Set X) (n : ℕ) :
    Submodule ℤ (SingularFree X n) :=
  Finsupp.supported ℤ ℤ {x | SmallSingularSimplex X A U n x}

theorem singularBarycentricIterate_eventually_small_submodule
    (X : TopCat) (A U : Set X) (hU : closure U ⊆ interior A)
    (n : ℕ) (c : SingularFree X n) :
    ∃ k : ℕ, singularBarycentricIterate X n k c ∈
      smallSingularChains X A U n := by
  obtain ⟨k, hk⟩ := singularBarycentricIterateList_eventually_small X A U hU n c
  refine ⟨k, ?_⟩
  rw [← iterateList_eq_iterate X n k c]
  intro x hx
  simpa [SmallSingularSimplex, Set.image_univ] using hk x hx

private theorem smallSingularSimplex_face (X : TopCat) (A U : Set X)
    (n : ℕ) (x : (TopCat.toSSet.obj X) _⦋n + 1⦌)
    (i : Fin (n + 2)) (hx : SmallSingularSimplex X A U (n + 1) x) :
    SmallSingularSimplex X A U n ((TopCat.toSSet.obj X).δ i x) := by
  have hrange : Set.range (TopCat.toSSetObjEquiv X (.op ⦋n⦌)
      ((TopCat.toSSet.obj X).δ i x)) ⊆
      Set.range (TopCat.toSSetObjEquiv X (.op ⦋n + 1⦌) x) := by
    intro z hz
    obtain ⟨t, rfl⟩ := hz
    exact ⟨StdSimplex.map i.succAbove t, rfl⟩
  rcases hx with h | h
  · exact Or.inl (hrange.trans h)
  · exact Or.inr (hrange.trans h)

theorem smallSingularChains_boundary (X : TopCat) (A U : Set X) (n : ℕ)
    (c : SingularFree X (n + 1))
    (hc : c ∈ smallSingularChains X A U (n + 1)) :
    singularBoundaryFinsupp X n c ∈ smallSingularChains X A U n := by
  classical
  have hsingle (x : (TopCat.toSSet.obj X) _⦋n + 1⦌)
      (hx : SmallSingularSimplex X A U (n + 1) x) :
      singularBoundaryFinsupp X n (Finsupp.single x 1) ∈
        smallSingularChains X A U n := by
    rw [singularBoundaryFinsupp_single]
    apply Submodule.sum_mem
    intro i hi
    apply Submodule.smul_mem
    exact Finsupp.single_mem_supported ℤ 1
      (smallSingularSimplex_face X A U n x i hx)
  have hrepr : c = ∑ x ∈ c.support, c x • Finsupp.single x 1 := by
    conv_lhs => rw [← Finsupp.sum_single c]
    simp [Finsupp.sum, Finsupp.smul_single]
  rw [hrepr]
  simp only [map_sum, map_smul]
  apply Submodule.sum_mem
  intro x hx
  apply Submodule.smul_mem
  exact hsingle x (hc hx)

/-- The boundary restricted to the actual small singular submodule. -/
noncomputable def smallSingularBoundary (X : TopCat) (A U : Set X) (n : ℕ) :
    smallSingularChains X A U (n + 1) →ₗ[ℤ]
      smallSingularChains X A U n :=
  (singularBoundaryFinsupp X n).comp
    (Submodule.subtype (smallSingularChains X A U (n + 1))) |>.codRestrict
      (smallSingularChains X A U n) (fun c =>
        smallSingularChains_boundary X A U n c.1 c.2)

private theorem smallSingularChains_of_imageSupported (X : TopCat)
    (A U : Set X) (n : ℕ) (S : Set X)
    (hS : S ⊆ Uᶜ ∨ S ⊆ A) (c : SingularFree X n)
    (hc : SingularChainImageSupported X n S c) :
    c ∈ smallSingularChains X A U n := by
  intro x hx
  rcases hS with h | h
  · exact Or.inl ((hc x hx).trans h)
  · exact Or.inr ((hc x hx).trans h)

private theorem smallSingularChains_linearMap (X : TopCat) (A U : Set X)
    (n m : ℕ) (F : SingularFree X n →ₗ[ℤ] SingularFree X m)
    (hF : ∀ x : (TopCat.toSSet.obj X) _⦋n⦌,
      SmallSingularSimplex X A U n x →
        F (Finsupp.single x 1) ∈ smallSingularChains X A U m)
    (c : SingularFree X n) (hc : c ∈ smallSingularChains X A U n) :
    F c ∈ smallSingularChains X A U m := by
  classical
  have hrepr : c = ∑ x ∈ c.support, c x • Finsupp.single x 1 := by
    conv_lhs => rw [← Finsupp.sum_single c]
    simp [Finsupp.sum, Finsupp.smul_single]
  rw [hrepr]
  simp only [map_sum, map_smul]
  apply Submodule.sum_mem
  intro x hx
  exact Submodule.smul_mem _ (c x) (hF x (hc hx))

private theorem singularSingle_imageSupported (X : TopCat) (n : ℕ)
    (S : Set X) (x : (TopCat.toSSet.obj X) _⦋n⦌)
    (hx : Set.range (TopCat.toSSetObjEquiv X (.op ⦋n⦌) x) ⊆ S) :
    SingularChainImageSupported X n S (Finsupp.single x 1) := by
  intro y hy
  have hxy : y = x := ((Finsupp.mem_support_single y x (1 : ℤ)).mp hy).1
  simpa [hxy] using hx

theorem smallSingularChains_barycentric (X : TopCat) (A U : Set X)
    (n : ℕ) (c : SingularFree X n)
    (hc : c ∈ smallSingularChains X A U n) :
    singularBarycentricFinsupp X n c ∈ smallSingularChains X A U n := by
  apply smallSingularChains_linearMap X A U n n
    (singularBarycentricFinsupp X n) ?_ c hc
  intro x hx
  rcases hx with hx | hx
  · exact smallSingularChains_of_imageSupported X A U n Uᶜ (Or.inl (by intro z hz; exact hz)) _
      (singularBarycentricFinsupp_supported X n Uᶜ _
        (singularSingle_imageSupported X n Uᶜ x hx))
  · exact smallSingularChains_of_imageSupported X A U n A (Or.inr (by intro z hz; exact hz)) _
      (singularBarycentricFinsupp_supported X n A _
        (singularSingle_imageSupported X n A x hx))

theorem smallSingularChains_carrierHomotopy (X : TopCat) (A U : Set X)
    (n : ℕ) (c : SingularFree X n)
    (hc : c ∈ smallSingularChains X A U n) :
    singularCarrierHomotopy X n c ∈ smallSingularChains X A U (n + 1) := by
  apply smallSingularChains_linearMap X A U n (n + 1)
    (singularCarrierHomotopy X n) ?_ c hc
  intro x hx
  rcases hx with hx | hx
  · exact smallSingularChains_of_imageSupported X A U (n + 1) Uᶜ
      (Or.inl (by intro z hz; exact hz)) _
      (singularCarrierHomotopy_supported X n Uᶜ _
        (singularSingle_imageSupported X n Uᶜ x hx))
  · exact smallSingularChains_of_imageSupported X A U (n + 1) A
      (Or.inr (by intro z hz; exact hz)) _
      (singularCarrierHomotopy_supported X n A _
        (singularSingle_imageSupported X n A x hx))

theorem smallSingularChains_barycentricIterate (X : TopCat) (A U : Set X)
    (n k : ℕ) (c : SingularFree X n)
    (hc : c ∈ smallSingularChains X A U n) :
    singularBarycentricIterate X n k c ∈ smallSingularChains X A U n := by
  induction k with
  | zero => simpa using hc
  | succ k ih =>
      rw [singularBarycentricIterate_succ]
      exact smallSingularChains_barycentric X A U n _ ih

theorem smallSingularChains_carrierHomotopyIterate (X : TopCat) (A U : Set X)
    (n k : ℕ) (c : SingularFree X n)
    (hc : c ∈ smallSingularChains X A U n) :
    singularCarrierHomotopyIterate X n k c ∈
      smallSingularChains X A U (n + 1) := by
  induction k with
  | zero => simp
  | succ k ih =>
      rw [singularCarrierHomotopyIterate_succ]
      exact (smallSingularChains X A U (n + 1)).add_mem ih
        (smallSingularChains_carrierHomotopy X A U n _
          (smallSingularChains_barycentricIterate X A U n k c hc))

/-- Cycles in the ordinary, non-augmented singular chain complex. -/
noncomputable def absoluteSingularCycles (X : TopCat) (n : ℕ) :
    Submodule ℤ (SingularFree X n) :=
  match n with
  | 0 => ⊤
  | k + 1 => LinearMap.ker (singularBoundaryFinsupp X k)

/-- The small cycles are the intersection of small chains with ambient cycles. -/
noncomputable def smallSingularCycles (X : TopCat) (A U : Set X) (n : ℕ) :
    Submodule ℤ (SingularFree X n) :=
  smallSingularChains X A U n ⊓ absoluteSingularCycles X n

theorem absoluteSingularCycles_boundary (X : TopCat) (n : ℕ)
    (c : SingularFree X (n + 1)) :
    singularBoundaryFinsupp X n c ∈ absoluteSingularCycles X n := by
  cases n with
  | zero => trivial
  | succ k =>
      change singularBoundaryFinsupp X k
        (singularBoundaryFinsupp X (k + 1) c) = 0
      exact singularBoundaryFinsupp_comp_zero X k c

private theorem absoluteSingularCycles_barycentricIterate (X : TopCat) (n k : ℕ)
    (c : SingularFree X n) (hc : c ∈ absoluteSingularCycles X n) :
    singularBarycentricIterate X n k c ∈ absoluteSingularCycles X n := by
  cases n with
  | zero => trivial
  | succ m =>
      change singularBoundaryFinsupp X m
        (singularBarycentricIterate X (m + 1) k c) = 0
      rw [singularBarycentricIterate_boundary]
      change singularBoundaryFinsupp X m c = 0 at hc
      rw [hc, map_zero]

private theorem singularCarrierHomotopyIterate_boundary_of_cycle
    (X : TopCat) (n k : ℕ) (c : SingularFree X n)
    (hc : c ∈ absoluteSingularCycles X n) :
    singularBoundaryFinsupp X n (singularCarrierHomotopyIterate X n k c) =
      singularBarycentricIterate X n k c - c := by
  cases n with
  | zero => exact singularCarrierHomotopyIterate_boundary_zero X k c
  | succ m =>
      have h := singularCarrierHomotopyIterate_boundary_succ X m k c
      change singularBoundaryFinsupp X m c = 0 at hc
      rw [hc, map_zero, add_zero] at h
      exact h

/-- Every ambient cycle has a homologous small cycle, with the actual
iterated subdivision as representative and carrier homotopy as witness. -/
theorem absoluteCycle_has_small_representative
    (X : TopCat) (A U : Set X) (hU : closure U ⊆ interior A)
    (n : ℕ) (c : SingularFree X n)
    (hc : c ∈ absoluteSingularCycles X n) :
    ∃ z : SingularFree X n, z ∈ smallSingularCycles X A U n ∧
      ∃ b : SingularFree X (n + 1),
        z - c = singularBoundaryFinsupp X n b := by
  obtain ⟨k, hk⟩ := singularBarycentricIterate_eventually_small_submodule
    X A U hU n c
  refine ⟨singularBarycentricIterate X n k c,
    ⟨hk, absoluteSingularCycles_barycentricIterate X n k c hc⟩,
    singularCarrierHomotopyIterate X n k c, ?_⟩
  exact (singularCarrierHomotopyIterate_boundary_of_cycle X n k c hc).symm

/-- A small cycle which bounds in the ambient complex already has a small
filling. A single subdivision depth is used for its ambient filling; the
carrier homotopy of the small boundary remains small at that same depth. -/
theorem smallCycle_has_small_filling
    (X : TopCat) (A U : Set X) (hU : closure U ⊆ interior A)
    (n : ℕ) (z : SingularFree X n)
    (hz : z ∈ smallSingularCycles X A U n)
    (b : SingularFree X (n + 1))
    (hb : singularBoundaryFinsupp X n b = z) :
    ∃ b' : SingularFree X (n + 1),
      b' ∈ smallSingularChains X A U (n + 1) ∧
      singularBoundaryFinsupp X n b' = z := by
  obtain ⟨k, hk⟩ := singularBarycentricIterate_eventually_small_submodule
    X A U hU (n + 1) b
  let b' := singularBarycentricIterate X (n + 1) k b -
    singularCarrierHomotopyIterate X n k z
  refine ⟨b', ?_, ?_⟩
  · exact (smallSingularChains X A U (n + 1)).sub_mem hk
      (smallSingularChains_carrierHomotopyIterate X A U n k z hz.1)
  · dsimp [b']
    rw [map_sub, singularBarycentricIterate_boundary, hb,
      singularCarrierHomotopyIterate_boundary_of_cycle X n k z hz.2]
    abel

/-- Ambient boundaries in degree `n`. -/
noncomputable def absoluteSingularBoundaries (X : TopCat) (n : ℕ) :
    Submodule ℤ (SingularFree X n) :=
  LinearMap.range (singularBoundaryFinsupp X n)

/-- Boundaries obtained from actual small chains, viewed in ambient chains. -/
noncomputable def smallSingularBoundaries (X : TopCat) (A U : Set X) (n : ℕ) :
    Submodule ℤ (SingularFree X n) :=
  LinearMap.range ((singularBoundaryFinsupp X n).comp
    (Submodule.subtype (smallSingularChains X A U (n + 1))))

/-- Ordinary singular homology, expressed as cycles modulo boundary range. -/
noncomputable abbrev absoluteSingularHomology (X : TopCat) (n : ℕ) : Type :=
  absoluteSingularCycles X n ⧸
    (absoluteSingularBoundaries X n).comap
      (Submodule.subtype (absoluteSingularCycles X n))

/-- Homology of the small singular subcomplex. -/
noncomputable abbrev smallSingularHomology (X : TopCat) (A U : Set X) (n : ℕ) : Type :=
  smallSingularCycles X A U n ⧸
    (smallSingularBoundaries X A U n).comap
      (Submodule.subtype (smallSingularCycles X A U n))

/-- The chain inclusion restricted to cycle modules. -/
noncomputable def smallCycleInclusion (X : TopCat) (A U : Set X) (n : ℕ) :
    smallSingularCycles X A U n →ₗ[ℤ] absoluteSingularCycles X n :=
  (Submodule.subtype (smallSingularCycles X A U n)).codRestrict
    (absoluteSingularCycles X n) (fun z => z.2.2)

/-- The map on homology induced by inclusion of the small chain complex. -/
noncomputable def smallHomologyInclusion (X : TopCat) (A U : Set X) (n : ℕ) :
    smallSingularHomology X A U n →ₗ[ℤ] absoluteSingularHomology X n :=
  Submodule.mapQ
    ((smallSingularBoundaries X A U n).comap
      (Submodule.subtype (smallSingularCycles X A U n)))
    ((absoluteSingularBoundaries X n).comap
      (Submodule.subtype (absoluteSingularCycles X n)))
    (smallCycleInclusion X A U n) (by
      intro z hz
      obtain ⟨b, hb⟩ := hz
      exact ⟨b.1, hb⟩)

theorem smallHomologyInclusion_surjective
    (X : TopCat) (A U : Set X) (hU : closure U ⊆ interior A)
    (n : ℕ) : Function.Surjective (smallHomologyInclusion X A U n) := by
  intro q
  let ab : Submodule ℤ (absoluteSingularCycles X n) :=
    (absoluteSingularBoundaries X n).comap
      (Submodule.subtype (absoluteSingularCycles X n))
  obtain ⟨z, rfl⟩ := ab.mkQ_surjective q
  obtain ⟨w, hw, b, hb⟩ :=
    absoluteCycle_has_small_representative X A U hU n z.1 z.2
  let ws : smallSingularCycles X A U n := ⟨w, hw⟩
  let qs : smallSingularHomology X A U n := QuotientAddGroup.mk' _ ws
  refine ⟨qs, ?_⟩
  change (QuotientAddGroup.mk' _ (smallCycleInclusion X A U n ws) :
    absoluteSingularHomology X n) = ab.mkQ z
  apply QuotientAddGroup.eq_iff_sub_mem.mpr
  change w - z.1 ∈ absoluteSingularBoundaries X n
  exact ⟨b, hb.symm⟩

theorem smallHomologyInclusion_injective
    (X : TopCat) (A U : Set X) (hU : closure U ⊆ interior A)
    (n : ℕ) : Function.Injective (smallHomologyInclusion X A U n) := by
  apply (LinearMap.ker_eq_bot).mp
  apply (LinearMap.ker_eq_bot').mpr
  intro q hzero
  let sb : Submodule ℤ (smallSingularCycles X A U n) :=
    (smallSingularBoundaries X A U n).comap
      (Submodule.subtype (smallSingularCycles X A U n))
  let ab : Submodule ℤ (absoluteSingularCycles X n) :=
    (absoluteSingularBoundaries X n).comap
      (Submodule.subtype (absoluteSingularCycles X n))
  obtain ⟨z, rfl⟩ := sb.mkQ_surjective q
  change ab.mkQ (smallCycleInclusion X A U n z) = 0 at hzero
  have hzker : smallCycleInclusion X A U n z ∈ LinearMap.ker ab.mkQ :=
    LinearMap.mem_ker.mpr hzero
  have hzab : smallCycleInclusion X A U n z ∈ ab := by
    simpa only [ab.ker_mkQ] using hzker
  have hzBound : z.1 ∈ absoluteSingularBoundaries X n := hzab
  obtain ⟨b, hb⟩ := hzBound
  obtain ⟨b', hbs, hbb⟩ :=
    smallCycle_has_small_filling X A U hU n z.1 z.2 b hb
  change (Submodule.Quotient.mk z : smallSingularHomology X A U n) = 0
  apply (Submodule.Quotient.mk_eq_zero sb).mpr
  change z.1 ∈ smallSingularBoundaries X A U n
  exact ⟨⟨b', hbs⟩, hbb⟩

/-- Inclusion of the actual small singular subcomplex induces an isomorphism
on the explicit cycle-modulo-boundary homology modules. -/
noncomputable def smallHomologyLinearEquiv
    (X : TopCat) (A U : Set X) (hU : closure U ⊆ interior A)
    (n : ℕ) :
    smallSingularHomology X A U n ≃ₗ[ℤ] absoluteSingularHomology X n :=
  LinearEquiv.ofBijective (smallHomologyInclusion X A U n)
    ⟨smallHomologyInclusion_injective X A U hU n,
      smallHomologyInclusion_surjective X A U hU n⟩

end CurveComplexGenusTwo.CWHurewicz
