import CurveComplexGenusTwo.Topology.GeometricPosition.WeightedBigonReplacement.ActualJordanDiskTools
import CurveComplexGenusTwo.Filtration.Geometry.ComponentGeometry
import Mathlib.Analysis.Convex.Contractible
import CurveComplexGenusTwo.Filtration.Geometry.ActualPuncturedJordanConversion
import Mathlib.AlgebraicTopology.FundamentalGroupoid.SimplyConnected
import CurveComplexGenusTwo.Topology.ActualGeometryRelease.ArcZeroRawSupportedCrosscutMove
import CurveComplexGenusTwo.Topology.ActualGeometryRelease.ArcZeroDiskBigonChartProducer
import CurveComplexGenusTwo.Topology.GlobalArcCollar.ActualFiniteInteriorAxisFraming
import CurveComplexGenusTwo.Topology.WeightedSurgery.MarkedArcReverse
import CurveComplexGenusTwo.Topology.ActualGeometryRelease.ArcZeroEmptyDiskCleanSides
import CurveComplexGenusTwo.Topology.ActualGeometryRelease.NonloopPrefixParameters
import CurveComplexGenusTwo.Topology.ActualGeometryRelease.NonloopPaddedRemainder
import CurveComplexGenusTwo.Topology.ActualGeometryRelease.NonloopBaseVanishingTracks
import CurveComplexGenusTwo.Topology.ActualGeometryRelease.NonloopClosedPieceDescent
import CurveComplexGenusTwo.Topology.IntersectionParity.EmptyDiskSidesStatement
import CurveComplexGenusTwo.Topology.ActualGeometryRelease.ArcZeroMarkedTwoSideDisk
import CurveComplexGenusTwo.Topology.ActualGeometryRelease.ArcZeroMarkedCrossingAfterClosedReplacement
import CurveComplexGenusTwo.Topology.Smoothing.MarkedTransport
set_option maxHeartbeats 4000000
namespace CurveComplex.HyperellipticModel
open Set Topology Schoenflies
open scoped BigOperators
variable {E S : Type} [TopologicalSpace E] [TopologicalSpace S]
  [ChartedSpace (EuclideanSpace ℝ (Fin 2)) E]



end CurveComplex.HyperellipticModel
